### PR TITLE
creating a category - Menu component for the products data

### PR DESCRIPTION
**Pull request by tuequach**
all category includes: 
- choys
- leaf
- fruit
- roots
- misc
- ❤

### CODE REVIEW

**Comment by tuequach** [comment]
categorymenu

**Comment by zenglenn42** [comment]
I checkout the category branch an see:

Screen Shot 2019-07-29 at 6 41 17 PM

**Comment by tuequach** [comment]
Image from iOS

- current category menu as of now

**Comment by zenglenn42** [comment]
I'm noticing the category bar is not centered:

Screen Shot 2019-07-29 at 6 41 17 PM

**Comment by zenglenn42** [comment]
Found better support for the sticky bottom behavior by using the AppBar component
Screen Shot 2019-08-07 at 1 48 01 PM

**Pull request merged**
